Feat/yr/registration api integration
wolox-training/yr-vue-angular pull request #13
Opened 2022-08-01 23:30 UTC by YgRamos9

## Summary
- implement registration API

## Screenshot
<img width="1076" alt="Captura de Pantalla 2022-08-01 a la(s) 6 29 25 p m" src="https://user-images.githubusercontent.com/107204529/182261947-4854b8e5-361e-4b53-a863-bd0f09ea1d47.png">

## Trello Card
https://trello.com/c/SseFp8Xv/3-registration-api-integration

2022-08-02 05:11 UTC, miguelhenaoa commented on angular/src/app/components/form-container/form-container.component.ts
> +  @Output() handleOnSubmit = new EventEmitter<IUser>();
💯

2022-08-02 15:28 UTC, joacomiguens commented on angular/src/app/screens/sign-up/sign-up.component.ts
> +        if (response.status === 201) {
use a global constant for 201 status code

2022-08-02 15:29 UTC, joacomiguens requested changes
Great work! Just a minor comment 😄

2022-08-03 19:12 UTC, joacomiguens commented on angular/src/app/constants/codeRequest.ts
> +  success = 1,
I think it should be 201 🤔

2022-08-03 19:19 UTC, joacomiguens approved these changes

2022-08-03 19:20 UTC, miguelhenaoa approved these changes

2022-08-04 03:29 UTC, merged