test(sign-up): testing component
wolox-training/yr-vue-angular pull request #14
Opened 2022-08-03 23:05 UTC by YgRamos9

## Summary
- adding unit tests

## Trello Card
https://trello.com/c/zVbA2x2X/17-tests-de-sign-up

2022-08-04 19:17 UTC, miguelhenaoa requested changes
Great job!!

2022-08-04 19:17 UTC, miguelhenaoa commented on angular/src/app/screens/sign-up/sign-up.component.spec.ts
> +import { SIGN_UP_FIELDS } from '../../constants/formAccount';
Sort imports

2022-08-04 19:17 UTC, miguelhenaoa commented on angular/src/app/screens/sign-up/sign-up.component.spec.ts
> +
Remove blank line

2022-08-04 19:17 UTC, miguelhenaoa commented on angular/src/app/screens/sign-up/sign-up.component.spec.ts
> +    });
Use addValueEvent

2022-08-04 19:17 UTC, miguelhenaoa commented on angular/src/app/screens/sign-up/sign-up.module.ts
> +  exports: [SignUpComponent, FormContainerComponent, CommonModule],
It's not necessary to export components if you not using them in an external module

2022-08-04 19:17 UTC, miguelhenaoa commented on angular/src/app/screens/sign-up/sign-up.component.spec.ts
> +    expect(createUserMock).toHaveBeenCalled();
Validate if the same data you enter are being sent

2022-08-05 13:32 UTC, joacomiguens commented on angular/src/app/screens/sign-up/sign-up.component.spec.ts
> +    expect(errorSpans).toHaveLength(5);
I prefer to map SIGN_UP_FIELDS errorSpans and check errorSpans variable includes them 😄

2022-08-05 13:34 UTC, joacomiguens commented on angular/src/app/services/user.service.spec.ts
> +    });
use Jest instead of Karma.

2022-08-05 13:34 UTC, joacomiguens commented on angular/src/app/app.component.spec.ts
>    });
Use jest in the file instead of Karma

2022-08-08 14:15 UTC, joacomiguens commented on angular/src/app/interfaces/global.interface.ts
> +  password_confirmation: string;
should be passwordConfirmation

2022-08-08 14:31 UTC, miguelhenaoa approved these changes

2022-08-08 14:38 UTC, joacomiguens approved these changes
Great Job!! Just a reminder, please upload code-coverage screenshot on PR description 🎸

2022-08-08 14:52 UTC, merged