feat(sessi): add component and unit test
wolox-training/yr-vue-angular pull request #16
Opened 2022-08-07 22:09 UTC by YgRamos9

## Summary
- adding unit tests

## Screenshot

## Trello Card
https://trello.com/c/eDUCaVcx/38-pull-request

2022-08-07 22:13 UTC, YgRamos9 commented
## Summary
- adding component auth

## Screenshot
<img width="1416" alt="Captura de Pantalla 2022-08-07 a la(s) 3 56 57 p m" src="https://user-images.githubusercontent.com/107204529/183312962-e64a3ce7-7d92-46c4-90b6-3ba7de21a9dc.png">

## Trello Card
https://trello.com/c/VtYKfim0/9-session-management-logout

2022-08-08 14:41 UTC, joacomiguens commented on angular/src/app/app.component.scss
> +
delete 😄

2022-08-08 14:45 UTC, joacomiguens commented on angular/src/app/screens/auth/auth.component.spec.ts
> +describe('Render auth component', () => {
I think you could test what happens when user logout

2022-08-08 14:47 UTC, joacomiguens commented on angular/src/app/screens/login/login.component.ts
> +import { Router } from '@angular/router';
must be at top

2022-08-08 14:48 UTC, joacomiguens commented on angular/src/app/screens/login/login.component.ts
> +  mensajeError!: string;
why? 🤔

2022-08-08 14:54 UTC, joacomiguens commented on angular/src/app/screens/login/login.component.ts
> +            this.userService.createSession(token);
You need to save access-token, uid, client. Storage it as an unique string in a single slot on localStorage 👌🏻

2022-08-08 14:54 UTC, joacomiguens commented on angular/src/app/services/user.service.ts
> +  signOff() {
```suggestion
  logOut() {
```

2022-08-08 14:55 UTC, joacomiguens commented on angular/src/app/services/user.service.ts
> +  isLogin() {
Do you use this function? 🖲️

2022-08-08 16:54 UTC, miguelhenaoa requested changes

2022-08-08 16:54 UTC, miguelhenaoa commented on angular/src/app/components/navbar/navbar.component.ts
> +  logOut() {
blank line

2022-08-08 16:54 UTC, miguelhenaoa commented on angular/src/app/services/user.service.ts
> +  createSession(token: string): void {
```suggestion
  setToken(token: string): void {
```

2022-08-08 20:13 UTC, joacomiguens approved these changes

2022-08-08 20:14 UTC, joacomiguens commented on angular/src/app/screens/auth/auth.component.spec.ts
> +describe('Render auth component', () => {
Do it on guards PR

2022-08-08 20:14 UTC, miguelhenaoa approved these changes

2022-08-08 20:42 UTC, merged