Feat/yr/auth and unauth guard
wolox-training/yr-vue-angular pull request #17
Opened 2022-08-09 20:57 UTC by YgRamos9

2022-08-10 06:25 UTC, miguelhenaoa commented
@YgRamos9, before reviewing the PR, add the coverage folder to the .gitignore file, for a more efficient review.

2022-08-10 16:21 UTC, miguelhenaoa requested changes

2022-08-10 16:21 UTC, miguelhenaoa commented on angular/src/app/components/form-container/form-container.component.ts
>    @Input() formGroup!: FormGroup;
The order of the decorators is Input first, then Output.

2022-08-10 16:21 UTC, miguelhenaoa commented on angular/src/app/guards/auth.guard.ts
> +  ActivatedRouteSnapshot,
Delete unused imports

2022-08-10 16:21 UTC, miguelhenaoa commented on angular/src/app/guards/unauth.guard.ts
> +  ActivatedRouteSnapshot,
Same

2022-08-10 16:21 UTC, miguelhenaoa commented on angular/src/app/guards/unauth.guard.ts
> +export class UnauthGuard implements CanActivate {
Rename UnAuthGuard

2022-08-10 18:36 UTC, joacomiguens commented on angular/src/app/services/user.service.ts
> +  isLogin() {
```suggestion
  isLogged() {
```

2022-08-10 18:37 UTC, joacomiguens commented on angular/src/app/screens/auth/screens/book-list/book-list.component.ts
> +  ngOnInit(): void {}
Delete unused methods please

2022-08-10 18:37 UTC, joacomiguens commented on angular/src/app/screens/auth/screens/book-list/book-list.component.scss
> +
delete file

2022-08-11 15:22 UTC, joacomiguens approved these changes

2022-08-11 16:24 UTC, miguelhenaoa approved these changes
LGTM!! 🚀

2022-08-11 16:30 UTC, merged