feat(book list)
wolox-training/yr-vue-angular pull request #18
Opened 2022-08-11 20:42 UTC by YgRamos9

## Summary
- add render book list

## Screenshot

https://user-images.githubusercontent.com/107204529/184238425-a91939e4-fe2d-4dab-8a4c-ab31206ac529.mov

## Trello Card
https://trello.com/c/mVkYVzdy/6-book-list-auth-header

2022-08-11 21:53 UTC, joacomiguens commented on angular/src/app/components/book-card/book-card.component.scss
> +}
Don't use mixin, add a new class

2022-08-11 22:01 UTC, joacomiguens commented on angular/src/styles/commons/buttons.scss
> +  border-radius: 2em;
use px

2022-08-11 22:04 UTC, joacomiguens commented on angular/src/app/pipes/filter-books.pipe.ts
> +    if (value) {
Delete this if, and add ? on value?.filter 😄

2022-08-11 22:05 UTC, joacomiguens commented on angular/src/app/screens/auth/auth-routing.module.ts
> +      },
BookList should be a module, like login or sign-up

2022-08-11 22:06 UTC, joacomiguens commented on angular/src/app/screens/auth/screens/book-list/book-list.component.html
> +    placeholder="Buscá por título del libro..." /><img class="book-icon-search" src="assets/search-icon.png"
<img> tag should be on next line.

2022-08-11 22:07 UTC, joacomiguens commented on angular/src/app/screens/auth/screens/book-list/book-list.component.html
> +  <ng-container *ngIf="(books | filterBooks: inputSearch).length === 0; else elseTemplate">
ngIf logic should be on component file

2022-08-11 22:09 UTC, joacomiguens commented on angular/src/app/screens/auth/screens/book-list/book-list.component.html
> +  <ng-container *ngIf="(books | filterBooks: inputSearch).length === 0; else elseTemplate">
Also, elseTemplate should be the worse case scenario. So I think we could change condition 👍🏻

2022-08-11 22:09 UTC, joacomiguens commented on angular/src/app/screens/auth/screens/book-list/book-list.component.scss
> +}
same here and reuse that new class you are going to create 🔝

2022-08-11 22:10 UTC, joacomiguens commented on angular/src/app/screens/auth/screens/book-list/book-list.component.spec.ts
> +describe('BoolistComponent ', () => {
```suggestion
describe('BookListComponent ', () => {
```

2022-08-11 22:11 UTC, joacomiguens commented on angular/src/app/screens/un-auth/un-auth-routing.module.ts
> +    redirectTo: 'login',
use enum 🛩️

2022-08-11 22:12 UTC, joacomiguens commented on angular/src/app/services/books.service.ts
> +      }),
```suggestion
      map((response: any) => response.page),
```

2022-08-11 22:14 UTC, joacomiguens commented on angular/src/app/services/user.service.ts
> +    };
```suggestion
    return localStorage.getItem('userToken') || {
      token: '',
      client: '',
      uid: '',
    };
```

2022-08-11 22:16 UTC, joacomiguens commented on angular/src/app/interfaces/global.interface.ts
> +}
This interface should be on camelCase format. So serialize request response 💯

2022-08-12 05:36 UTC, miguelhenaoa requested changes

2022-08-12 05:36 UTC, miguelhenaoa commented on angular/src/app/components/book-card/book-card.component.html
> +  <div class="book-author">{{ book.author }}</div>
use span

2022-08-12 05:36 UTC, miguelhenaoa commented on angular/src/app/screens/auth/screens/book-list/book-list.component.html
> +  <input class="book-search-input" name="inputSearch" role="search" [(ngModel)]="inputSearch" type="search"
Format this tag, one property by line

2022-08-12 05:36 UTC, miguelhenaoa commented on angular/src/app/screens/un-auth/un-auth.component.html
> +<p>un-auth works!</p>
is that what this is used for?

2022-08-12 16:50 UTC, miguelhenaoa commented on angular/src/app/screens/auth/screens/book-list/book-list.component.ts
> +  trackByBooks(index: number, item: IBook): number {
Remove unused param

2022-08-12 16:50 UTC, miguelhenaoa commented on angular/src/app/screens/auth/screens/book-list/book-list.component.ts
> +  inputSearch!: any;
Add type

2022-08-12 18:31 UTC, miguelhenaoa requested changes

2022-08-12 18:31 UTC, miguelhenaoa commented on angular/src/app/screens/auth/screens/book-list/book-list.component.scss
> +.book-empy {
```suggestion
.book-empty {
```

2022-08-12 18:31 UTC, miguelhenaoa commented on angular/src/app/screens/auth/screens/book-list/book-list.component.scss
> +  border: 2px solid #e8e8e8;
this to colors.scss

2022-08-12 18:31 UTC, miguelhenaoa commented on angular/src/app/services/books.service.ts
> +  private API: string = environment.apiUrl;
```suggestion
  private readonly API: string = environment.apiUrl;
```

2022-08-12 19:41 UTC, joacomiguens commented on angular/src/app/helpers/mocks/mock-books.ts
> +  },
should be in camelCase

2022-08-12 19:49 UTC, joacomiguens commented on angular/src/app/screens/auth/screens/book-list/book-list.component.ts
> +  }
should be after ngOnInit

2022-08-12 19:56 UTC, joacomiguens approved these changes

2022-08-16 14:01 UTC, miguelhenaoa approved these changes
LGTM!! 🚀

2022-08-16 14:44 UTC, merged